language: php 

php:
  - 7.0
  - 7.1
  - 7.2

notifications:
  email: false

sudo: enabled

# Compile
before_script:
  - ./travis/install-deps.sh
  - ./travis/compile.sh

# Run PHPs run-tests.php 
script:
  - ./travis/run-test.sh